apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n
  namespace: self-hosted
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: n8n
    creationPolicy: 'Orphan'
  data:
  - secretKey: DB_POSTGRESDB_USER
    remoteRef:
      key: kube/n8n
      property: DB_POSTGRESDB_USER
  - secretKey: DB_POSTGRESDB_PASSWORD
    remoteRef:
      key: kube/n8n
      property: DB_POSTGRESDB_PASSWORD
  - secretKey: N8N_ENCRYPTION_KEY
    remoteRef:
      key: kube/n8n
      property: N8N_ENCRYPTION_KEY