kind: "DatadogAgent"
apiVersion: "datadoghq.com/v2alpha1"
metadata:
  name: "datadog"
spec:
  global:
    site: "datadoghq.com"
    credentials:
      apiSecret:
        secretName: "datadog-secret"
        keyName: "api-key"
    clusterName: "talos-k8s"
  features:
    apm:
      instrumentation:
        enabled: true
    logCollection:
      enabled: true
      containerCollectAll: true
